### ISSUE TITLE
Segfault when reweighting decay branching ratios for P33(1600)

### ISSUE THREAD

**Issue by sjgardiner** [GENIE-MC/Reweight#10]
Recent fixes on the Generator master branch allow RES events involving production of P33(1600) to be simulated correctly (see GENIE docDB #153 for a description of the issue discovered in R-3_00_06). When either of the two Reweight knobs varying resonance decay branching ratios (`RDecBR1gamma` and `RDecBR1eta`) are used with these events, however, a segfault occurs in `GReWeightResonanceDecay::RewBR()`.

The segfault occurs because `kPdgP33m1600_DeltaP` (and the other Δ(1600) PDG codes) are missing from a hard-coded list of resonances in `GReWeightResonanceDecay.cxx`. As a result, a `TH1D` needed for the branching ratio calculations is not produced and leads to an attempt to dereference a nullptr.

At a minimum, the resonance PDG code list in `Reweight/src/RwCalculators/GReWeightResonanceDecay.cxx` should be brought up to date with the master branch of Generator. It would be better to remove the hard-coded list in favor of a solution that is easier to maintain.

**Comment by mroda88** [comment]
Now going in with #18
