### ISSUE TITLE
Compile needs a header file spec moved from .cxx to .h

### ISSUE THREAD

**Issue by rikgran** [GENIE-MC/Reweight#20]
Oh, this might be mistaken, haven't deleted it yet.   My installation had not created an include directory (which is sometimes optional, but possibly not optional for using this package).

Simple fix:

The src/RwCalculators/GReWeightINuke.h
needs
#include "Framework/GHEP/GHepParticle.h"
because its part of the method CalcDeltaAZ specified in the .h file

Having it in the .cxx file is not enough, compiler gives unknown type name

Using AlmaLinux 9.1

**Comment by nusense** [comment]
resolved
